name: Unzip archivo

on:
  push:
    branches:
      - main

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install unrar
        run: |
          sudo apt-get update
          sudo apt-get install -y unrar
      - name: Unzip archivo
        run: |
          unrar x SP.rar
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Unzip archivo"
